[package]
name = "ml-rust-cuda"
version = "0.1.0"
authors = ["Arjun Raghavan <arjun.raghavan.2k@gmail.com>"]
edition = "2018"

[dependencies]
libc = "0.2"
rand = "0.8"

[build-dependencies]
cc = "1.0"
